--- #----------------Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-quatation-service
    enviroment: dev
  name: demo-quatation-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo-quatation-service
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo-quatation-service
    spec:
      containers:
        - name: demo-quatation-service
          image: botany7643/demo-quatation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /quatation-service/swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 8
          readinessProbe:
            httpGet:
              path: /quatation-service/swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 8
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 10

