#---------------- Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-quatation-service
  name: demo-quatation-service-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: demo-quatation-service-svc
    port: 80
    targetPort: 8080
  selector:
    app: demo-quatation-service